#!/bin/bash

# Initialize an empty array to hold modified arguments
args=()

o_args=$@

# Process and potentially modify the arguments
while [ $# -gt 0 ]; do
    if [ "$1" == "-d" ] && [ "$2" == "ata" ]; then
        args+=("-d")
        args+=("sat")
        shift 2
    else
        args+=("$1")
        shift
    fi
done

output=$(/bin/smartctl-binary "${args[@]}")

# Fall back if something went wrong
if [ $? -eq 0 ]; then
        echo "Output: $output"
else
        /bin/smartctl-binary ${o_args}
fi

# Execute /bin/smartctl-binary with the modified arguments
#/bin/smartctl-binary "${args[@]}"
